-- AlterTable
ALTER TABLE "ExpressionOfInterest" ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMPTZ(3);

-- AlterTable
ALTER TABLE "OutboxEvent" ALTER COLUMN "occurredAt" SET DATA TYPE TIMESTAMPTZ(3),
ALTER COLUMN "publishedAt" SET DATA TYPE TIMESTAMPTZ(3);

-- AlterTable
ALTER TABLE "Selection" ALTER COLUMN "selectedAt" SET DATA TYPE TIMESTAMPTZ(3),
ALTER COLUMN "resolvedAt" SET DATA TYPE TIMESTAMPTZ(3);
